services:
  - type: web
    name: word-game
    env: elixir
    region: frankfurt
    plan: free
    buildCommand: |
      mix deps.get
      mix compile
    startCommand: mix phx.server
    envVars:
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: PHX_HOST
        fromService:
          type: web
          name: word-game
          property: host
      - key: PORT
        value: 4000
    healthCheckPath: /
    autoDeploy: true